# PRACTICE SET 1 CREATE DATABASE AND TABLE INSERT VALUES 
CREATE DATABASE COLLEGEDB;
USE COLLEGEDB;

CREATE TABLE STUDENTS (
STUDENT_ID INT PRIMARY KEY ,
NAME VARCHAR(50) ,
DOB DATE ,
MARKS INT ,
CITY VARCHAR(40)
);

INSERT INTO STUDENTS VALUES
(1,"AFTAB","2005-12-25",85,"KANPUR"),
(2,"ANKIT","2005-07-11",92,"AZAMGARH"),
(3,"PRIYA","2004-05-20",76,"DELHI"),
(4,"RAHUL","2003-11-15",60,"KANPUR"),
(5,"NEHA","2006-01-05",88,"MUMBAI");

SELECT * FROM STUDENTS;

#PRACTICE SET 2
# SHOW NAMES IN UPPERCASE , LOWERCASE , SHOW FIRST 3 LETTERS EACH NAME , NAME-CITY TOGETHER
SELECT UPPER(NAME) FROM STUDENTS ;
SELECT LOWER(NAME) FROM STUDENTS ;
SELECT SUBSTRING(NAME,1,3) FROM STUDENTS ;
SELECT CONCAT(NAME , "-" , CITY ) FROM STUDENTS ;

# PRACTICE SET - 3
# SHOW MARKS ROUNDED TO NEAREST 10 , ABSOUTE VALUE OF MARKS , SQUARE OF MARKS 
SELECT ROUND(MARKS,-1) FROM STUDENTS ;
SELECT ABS(MARKS -100) FROM STUDENTS ;
SELECT POWER(MARKS , 2) FROM STUDENTS ;

#PRACICE SET - 4
#SHOW DOB AND CURRENT DATE , CALCULATE AGE OF EACH STUDENT
SELECT NAME , DOB , NOW() FROM STUDENTS ;
SELECT NAME , TIMESTAMPDIFF(YEAR , DOB , CURDATE()) AS AGE FROM STUDENTS ;

#PRACTICE - 5
# COUNT TOTAL STUDENTS , SHOW HIGHEST MARKS , SHOW AVERAGE MARKS , SHOW TOTAL MARKS OF ALL STUDENTS 
SELECT COUNT(*) FROM STUDENTS ;
SELECT MAX(MARKS) FROM STUDENTS ;
SELECT AVG(MARKS) FROM STUDENTS ;
SELECT SUM(MARKS) FROM STUDENTS ;

# PRACTICE - 6
# GROUP BY + HAVING CLAUSE 
# COUNT STUDENTS CITY WISE , AVERAGE MARKS CITY WISE , SHOW CITIES WHERE AVG MARKS >80 

SELECT CITY , COUNT(*) AS TOTALSTUDENTS FROM STUDENTS GROUP BY CITY ;
SELECT CITY , AVG(MARKS) AS AVGMARKS FROM STUDENTS GROUP BY CITY ;
SELECT CITY , AVG(MARKS) AS AVGMARKS FROM STUDENTS GROUP BY CITY HAVING AVG(MARKS) >80 ;

#PRACTICE - 7
# DETERMINSTIC VS NON DETERMINSTIC
SELECT ABS(-20); #DETERMINSTIC
SELECT NOW(); #NON-DETERMINSTIC
SELECT RAND() ; #N0N-DETERMINSTIC

# MYSQL-UDF
# A - SCALER FUNCTION
DELIMITER $$
CREATE FUNCTION GETGRADE( MARKS INT )
RETURNS VARCHAR(10)
DETERMINISTIC 
BEGIN
DECLARE GRADE VARCHAR(10);
IF MARKS >=90 THEN
SET GRADE = "A" ;
ELSEIF MARKS >=75 THEN
SET GRADE = "B" ;
ELSEIF MARKS >=50 THEN
SET GRADE = "C" ;
ELSE 
SET GRADE = "FAIL" ;
END IF ;
RETURN GRADE ;
END $$
DELIMITER ;

SELECT NAME , MARKS , GETGRADE(MARKS) AS GRADE FROM STUDENTS ;

# TABLE VALUED STYLE FUNCTION
CREATE VIEW STUDENTS_KANPUR AS
SELECT * FROM STUDENTS WHERE CITY = "KANPUR" ;
# USE
SELECT * FROM STUDENTS_KANPUR ;


# STORED PROCEDURE
DELIMITER $$
CREATE PROCEDURE ADDSTUDENT(
IN p_ID INT ,
IN p_NAME VARCHAR(50) ,
IN p_DOB DATE ,
IN p_MARKS INT ,
IN p_CITY VARCHAR(40)
)
BEGIN 
INSERT INTO STUDENTS VALUES ( p_ID , p_NAME , p_DOB , p_MARKS , p_CITY );
END $$
DELIMITER ;

CALL ADDSTUDENT(6,"RIYA","2005-10-10",79,"DELHI");

# CUSTOM AGE FUNCTION
CREATE FUNCTION GETAGE(DOB DATE)
RETURNS INT
DETERMINISTIC
BEGIN 
RETURN TIMESTAMPDIFF(YEAR , DOB , CURDATE())
END $$
DELIMITER ;

SELECT NAME , GETAGE(DOB) AS AGE FROM STUDENTS ;