CREATE DATABASE INDEXING ;
USE INDEXING ;

CREATE TABLE EMPLOYEES ( 
EMP_ID INT PRIMARY KEY ,
NAME VARCHAR(50) ,
EMAIL VARCHAR(100) ,
DEPARTMENT VARCHAR(30) ,
SALARY INT ,
CITY VARCHAR(30) ,
JOINING_DATE DATE 
);

INSERT INTO EMPLOYEES VALUES 
( 1 ,"ANKIT", "ANKIT@GMAIL.COM" , "IT" , 50000 , "DELHI" , '2026-01-10') ,
( 2 ,"RAHUL", "RAHUL@GMAIL.COM" , "HR" , 40000 , "MUMBAI" , '2021-05-15') ,
(3, 'Priya', 'priya@gmail.com', 'Finance', 60000, 'Delhi', '2020-03-20'),
(4, 'Aman', 'aman@gmail.com', 'IT', 55000, 'Pune', '2022-07-18'),
(5, 'Neha', 'neha@gmail.com', 'HR', 45000, 'Mumbai', '2021-11-05'),
(6, 'Ravi', 'ravi@gmail.com', 'Finance', 70000, 'Bangalore', '2019-08-25'),
(7, 'Simran', 'simran@gmail.com', 'IT', 65000, 'Delhi', '2023-02-12'),
(8, 'Vikas', 'vikas@gmail.com', 'Sales', 48000, 'Pune', '2020-12-30'),
(9, 'Pooja', 'pooja@gmail.com', 'Sales', 52000, 'Mumbai', '2022-06-09'),
(10, 'Karan', 'karan@gmail.com', 'IT', 75000, 'Bangalore', '2018-04-01');

# CREATE NORMAL INDEX 

CREATE INDEX IDX_DEPARTMENT ON EMPLOYEES(DEPARTMENT);
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = "IT";

# CREATE UNIQUE INDEX

CREATE UNIQUE INDEX IDX_EMAIL 
ON EMPLOYEES ( EMAIL );

#PURPOSE TO CHECK DUPLICATE VALUE RESTRICTIONS

INSERT INTO EMPLOYEES VALUES (10, 'Karan', 'karan@gmail.com', 'IT', 75000, 'Bangalore', '2018-04-01');
SELECT * FROM EMPLOYEES WHERE EMAIL = " 10, 'Karan', 'karan@gmail.com', 'IT', 75000, 'Bangalore', '2018-04-01'";

#COMPOSITE INDEX

CREATE INDEX IDX_DEPT_CITY ON EMPLOYEES( DEPARTMENT , CITY );
SELECT * FROM EMPLOYEES WHERE DEPARTMENT = "IT" AND CITY =  "DELHI";

CREATE INDEX IDX_SALARY ON EMPLOYEES (SALARY);
SELECT * FROM EMPLOYEES WHERE SALARY >60000;

#FOR SHOW ALL INDEXES 
SHOW INDEX FROM EMPLOYEES;

# DROP THIS INDEX
DROP INDEX IDX_SALARY ON EMPLOYEES;

#INDEX check 
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT = "HR";  

# TRY TO BITMAP INDEXING

CREATE TABLE GENDER ( 
ROW_ID INT , GENDER CHAR(1) 
);

INSERT INTO GENDER VALUES 
(1,"M"),
(2,"F"),
(3,"M"),
(4,"F");

SELECT * FROM GENDER WHERE GENDER = 'M';

# FUNCTION BASED INDEXING 
SELECT * FROM EMPLOYEES
WHERE LOWER(NAME) = "ankit";

# HASH FUNCTION

CREATE TABLE users (
    id INT,
    username VARCHAR(50),
    INDEX(username) USING HASH
) ENGINE = MEMORY;

SELECT * FROM users WHERE username = 'ankit';

CREATE TABLE students (
    roll_no INT PRIMARY KEY,
    name VARCHAR(50)
);

