CREATE DATABASE customer;
USE customer;
CREATE TABLE customer (
customer_id INT ,
customer VARCHAR(50),
mode VARCHAR(50),
city VARCHAR(50)
);

INSERT INTO customer
( customer_id , customer , mode , city )
VALUES
(101,"OLIVIA BARRETT","NETBANKING","PORTLAND"),
(102,"ETHAN SINCLAIR","CREDIT CARD","MIAMI"),
(103,"MAYA HERNADEZ","CREDIT CARD","SEATTLE"),
(104,"LIAM DONOVAN","NETBANKING","DENVER"),
(105,"SOPHIA NGUYEN","CREDIT CARD","NEW ORLEANS"),
(106,"COLEB FASTER ","DEBIT CARD","MINNEAPOLIS"),
(107,"AVA PATEL","DEBIT CARD","PHONEIX" ),
(108,"LUCAS CARTER","NETBANKING","BOSTON"),
(109,"JSABELLA MARTINEZ","NETBANKING","NASHVILLE"),
(110,"JACKSON BROOKS","CREDIT CARD","BOSTON");
SELECT * FROM customer;

SELECT mode , count(customer_id) FROM customer GROUP BY mode;