# STORED PROCEDURE 
# CREATE TABLE FIRST 

CREATE DATABASE STORED_PROCEDURE ;
USE STORED_PROCEDURE ;

CREATE TABLE STUDENTS (
ID INT PRIMARY KEY , 
NAME VARCHAR(50) ,
MARKS INT 
);

INSERT INTO STUDENTS VALUES
(1,"AFTAB",85),
(2,"ANKIT",92),
(3,"RIYA",70);

# SIMPLE SELECT PROCEDUER

DELIMITER $$
CREATE PROCEDURE GETSTUDENTS()
BEGIN 
SELECT * FROM STUDENTS;
END $$
DELIMITER ;

CALL GETSTUDENTS();

# PROCEDURE WITH INPUT

DELIMITER $$
CREATE PROCEDURE GETSTUDENTBY_ID ( IN S_ID INT )
BEGIN
SELECT * FROM STUDENTS
WHERE ID = S_ID ;
END $$
DELIMITER ;

CALL GETSTUDENTBY_ID(2);

# INSERT USING STORED PROCEDURE

DELIMITER $$
CREATE PROCEDURE ADDSTUDENT( IN S_ID INT , IN S_NAME VARCHAR(50) , IN S_MARKS INT )
BEGIN
INSERT INTO STUDENTS ( ID , NAME , MARKS )
VALUES ( S_ID , S_NAME , S_MARKS );
END $$
DELIMITER ;

CALL ADDSTUDENT (4,"NEHA",88);
SELECT * FROM STUDENTS ;

# OUTPUT PARAMETER 

DELIMITER $$
CREATE PROCEDURE GETTOPMARKS ( OUT TOP_MARK INT )
BEGIN 
SELECT MAX(MARKS) INTO TOP_MARK
FROM STUDENTS ;
END $$
DELIMITER ;

CALL GETTOPMARKS(@M);
SELECT @M;