# TCL TRANSCATION COMMAND LANGUAGE 

CREATE DATABASE TCL;
USE TCL;

CREATE TABLE ACCOUNTS (
ACC_ID INT PRIMARY KEY ,
NAME VARCHAR (50) ,
BALANCE INT 
);

INSERT INTO ACCOUNTS VALUES
( 1 , "ANKIT" , 10000 ) ,
( 2 , "RAHUL" , 8000 ) ,
( 3 , "PRIYA" , 12000 );

SELECT * FROM ACCOUNTS ;

SET AUTOCOMMIT = 0;

# TRANSCATION COMMIT 

START TRANSACTION ;
UPDATE ACCOUNTS SET BALANCE = BALANCE - 2000
WHERE ACC_ID = 1;

UPDATE ACCOUNTS SET BALANCE = BALANCE + 2000 WHERE ACC_ID = 2;

# ROLLBACK

START TRANSACTION ;
UPDATE ACCOUNTS SET BALANCE = BALANCE - 5000 WHERE ACC_ID = 3; # ACC_ID 3 IS PRIYA WE PERFORM ROLLBACK OPERATION ON PRIYA BECAUSE 1 AND 2 ARE COMMITED AND COMMITS NOT GET ROLLBACK
ROLLBACK; # AFTER UPDATE PRIYA HAS A AMOUNT 7000 BUT WHEN PERFORM ROLLBACK IT GETS AGAIN 12000 ORIGINAL VALUE

# SAVEPOINT
 START TRANSACTION ;
 UPDATE ACCOUNTS SET BALANCE = BALANCE - 1000 WHERE ACC_ID = 1;
 SAVEPOINT SP1;
UPDATE ACCOUNTS SET BALANCE = BALANCE - 3000 WHERE ACC_ID = 2;
SAVEPOINT SP2;
ROLLBACK TO SP1; # SP1 PERFORM UPDATE PERFORM OPERATION BUT UPDATE 2 GETS ROLLBACKED NO CHANGE
COMMIT;
SELECT * FROM ACCOUNTS;
