CREATE DATABASE COLLGEDB ;
USE COLLEGEDB ;

CREATE TABLE STUDENT (
ID INT PRIMARY KEY AUTO_INCREMENT ,
NAME VARCHAR(50) ,
MARKS INT 
);

CREATE TABLE DELETED_STUDENTS (
ID INT ,
NAME VARCHAR(50) , 
MARKS INT ,
DELETED_ON DATETIME
);

CREATE TABLE MARKS_LOG (
ID INT ,
OLD_MARKS INT ,
NEW_MARKS INT ,
UPDATED_ON DATETIME
);

# BEFORE INSERT TRIGGER
# Make sure no one inserts negative marks.
DELIMITER $$
CREATE TRIGGER BEFORE_INSERT_MARKS
BEFORE INSERT ON STUDENT 
FOR EACH ROW
BEGIN
IF NEW.MARKS < 0 THEN
SET NEW.MARKS = 0;
END IF ;
END $$
DELIMITER ;

# AFTER UPDATE TRIGGER
# Save old + new marks into log table.
DELIMITER $$
CREATE TRIGGER AFTER_UPDATE_MARKS 
AFTER UPDATE ON STUDENT 
FOR EACH ROW
BEGIN
INSERT INTO MARKS_LOG ( ID , OLD_MARKS , NEW_MARKS , UPDATED_ON )
VALUES ( OLD.ID , OLD.MARKS , NEW.MARKS , NOW());
END $$
DELIMITER ;

# AFTER DELETE TRIGGER
# Move deleted student to backup table.
DELIMITER $$
CREATE TRIGGER AFTER_DELETE_STUDENT
AFTER DELETE ON STUDENT 
FOR EACH ROW 
BEGIN
INSERT INTO DELETED_STUDENTS ( ID , NAME , MARKS , DELETED_ON )
VALUES ( OLD.ID , OLD.NAME , OLD.MARKS , NOW());
END $$
DELIMITER ;

INSERT INTO STUDENT ( NAME , MARKS )
VALUES ( "AMAN" , 70 ) ,
( "RIYA" , -20 );

SELECT * FROM STUDENT ;

# TEST AFTER UPDATE 
UPDATE STUDENT
SET MARKS = 90
WHERE ID = 1 ;

# CHECK MARKS_LOG
SELECT * FROM MARKS_LOG ;

# TEST AFTER DELETE 
DELETE FROM STUDENT
WHERE ID = 2 ;

# CHECK BACKUP TABLE 
SELECT * FROM DELETED_STUDENTS ;

/* # SUMMARY
1️ CREATE DATABASE
2️ CREATE TABLES
3️ CREATE TRIGGERS
4️ INSERT — trigger fires BEFORE
5️ UPDATE — trigger fires AFTER
6️ DELETE — trigger fires AFTER 
/*