# ADD TWO SUM FUNCTION
DELIMITER $$
CREATE FUNCTION ADDTWO(A INT , B INT )
RETURNS INT 
DETERMINISTIC
BEGIN
RETURN A+B;
END $$
DELIMITER ;

# USE
SELECT ADDTWO(10,20)

# SUBTRACT TWO SUM FUNCTION
DELIMITER $$
CREATE FUNCTION SUBTRACT( A INT , B INT )
RETURNS INT 
DETERMINISTIC
BEGIN
RETURN A - B;
END $$
DELIMITER ;

SELECT SUBTRACT(30,20);

# SQUARE FUNCTION
DELIMITER $$
CREATE FUNCTION SQUARE( N INT )
RETURNS INT
DETERMINISTIC 
BEGIN
RETURN N*N;
END $$
DELIMITER ;

SELECT SQUARE(5);

# GETAGE FROM DOB
DELIMITER $$
CREATE FUNCTION GET_AGE( DOB DATE)
RETURNS INT  
DETERMINISTIC 
BEGIN
RETURN TIMESTAMPDIFF( YEAR , DOB , CURDATE());
END $$
DELIMITER ;

SELECT NAME , DOB ,   GETAGE(DOB) AS AGE FROM STUDENTS ;

# GRADE CALCULATOR
DELIMITER $$
CREATE FUNCTION GET_GRADE(MARKS INT )
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
DECLARE GRADE VARCHAR(10);
IF MARKS >-90 THEN 
SET GRADE = "A";
ELSEIF MARKS >=75 THEN
SET GRADE = "B";
ELSEIF MARKS >=50 THEN 
SET GRADE = "C";
ELSE 
SET GRADE = "FAIL";
END IF ;
RETURN GRADE ;
END $$
DELIMITER ;

SELECT NAME , MARKS , GET_GRADE(MARKS) AS GRADE FROM STUDENTS ;

# CALCULATE PERCENTAGE 
# PERCENTAGE = MARKS/TOTAL*100

DELIMITER $$
CREATE FUNCTION CALCULATEPERCENTAGE( MARKS INT , TOTAL INT )
RETURNS DECIMAL(6,2)
DETERMINISTIC
BEGIN
RETURN ( MARKS * 100.0)/TOTAL;
END $$
DELIMITER ;

SELECT NAME , CALCULATEPERCENTAGE(MARKS , 100 ) AS PERCENTAGE FROM STUDENTS ;

# FORMAT FULL NAME 
DELIMITER $$
CREATE FUNCTION FULLNAME(FIRST VARCHAR(30) , LAST VARCHAR(30))
RETURNS VARCHAR(70)
DETERMINISTIC 
BEGIN
RETURN CONCAT(UPPER(FIRST),' ' , UPPER(LAST));
END $$
DELIMITER ;

SELECT FULLNAME( 'ANKIT' , 'SONKAR' );

# CHECK PASS/FAIL ( BOOLEAN STYLE )
DELIMITER $$
CREATE FUNCTION ISPASS(MARKS INT )
RETURNS VARCHAR(10)
DETERMINISTIC 
BEGIN
IF MARKS >=33 THEN
RETURN 'PASS';
ELSE 
RETURN 'FAIL' ;
END IF ;
END $$
DELIMITER ;

SELECT NAME , MARKS , ISPASS(MARKS) FROM STUDENTS ;

DROP FUNCTION IF EXISTS GETAGE ;

/*Create functions:

getStatus(marks)
Return:

Distinction (>=85)

First Class (>=60)

Second Class (>=45)
Fail
*/

DELIMITER $$
CREATE FUNCTION GETSTATUS(MARKS INT )
RETURNS VARCHAR(20) 
DETERMINISTIC
BEGIN
DECLARE GRADE VARCHAR(20);
IF MARKS >=85 THEN
SET GRADE = "DISTINCTION" ;
ELSEIF MARKS >=60 THEN
SET GRADE = "FIRST CLASS ";
ELSEIF MARKS >=45 THEN
SET GRADE = "SECOND CLASS ";
ELSE 
SET GRADE = "FAIL";
END IF ;
RETURN GRADE;
END $$
DELIMITER ;

SELECT GETSTATUS(92);
SELECT GETSTATUS(70);
SELECT GETSTATUS(40);

/* getInitials(name)
Example:

"Ankit Sonkar" → "A.S."
*/

DELIMITER $$
CREATE FUNCTION GET_INITIALS(FULLNAME VARCHAR(100))
RETURNS VARCHAR(10)
DETERMINISTIC 
BEGIN
DECLARE FIRST VARCHAR(50);
DECLARE LAST VARCHAR(50);
SET FIRST = SUBSTRING_INDEX(FULLNAME,' ' , 1);
SET LAST = SUBSTRING_INDEX(FULLNAME, ' ' ,-1);
RETURN CONCAT(
LEFT(UPPER(FIRST),1),'_',
LEFT(UPPER(LAST),1),'_'
);
END $$
DELIMITER ;
RETURN CONCAT(UPPER LEFT(NAME , 1 ) , ' ' UPPER(LEFT(NAME , 1))
END $$
DELIMITER ;

SELECT GET_INITIALS("ANKIT SONKAR");
SELECT GET_INITIALS('AFTAB ANSARI');

DROP FUNCTION GETINITIALS;